/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    staff: StaffAuthOperations;
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    staff: Staff;
    users: User;
    'access-providers': AccessProvider;
    media: Media;
    sectors: Sector;
    products: Product;
    subjects: Subject;
    locations: Location;
    sources: Source;
    articles: Article;
    bills: Bill;
    trademarks: Trademark;
    countries: Country;
    datasets: Dataset;
    'dataset-rows': DatasetRow;
    guides: Guide;
    'guide-files': GuideFile;
    publications: Publication;
    'publication-issues': PublicationIssue;
    'email-flags': EmailFlag;
    'trademark-import-runs': TrademarkImportRun;
    'mailchimp-outbox': MailchimpOutbox;
    speakers: Speaker;
    sponsors: Sponsor;
    events: Event;
    sessions: Session;
    'discount-codes': DiscountCode;
    orders: Order;
    'event-registrations': EventRegistration;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      registrations: 'event-registrations';
    };
    'access-providers': {
      users: 'users';
    };
    sponsors: {
      events: 'events';
    };
    events: {
      sessions: 'sessions';
    };
    'discount-codes': {
      uses: 'event-registrations';
    };
    orders: {
      registrations: 'event-registrations';
    };
  };
  collectionsSelect: {
    staff: StaffSelect<false> | StaffSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'access-providers': AccessProvidersSelect<false> | AccessProvidersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    sectors: SectorsSelect<false> | SectorsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    subjects: SubjectsSelect<false> | SubjectsSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    sources: SourcesSelect<false> | SourcesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    bills: BillsSelect<false> | BillsSelect<true>;
    trademarks: TrademarksSelect<false> | TrademarksSelect<true>;
    countries: CountriesSelect<false> | CountriesSelect<true>;
    datasets: DatasetsSelect<false> | DatasetsSelect<true>;
    'dataset-rows': DatasetRowsSelect<false> | DatasetRowsSelect<true>;
    guides: GuidesSelect<false> | GuidesSelect<true>;
    'guide-files': GuideFilesSelect<false> | GuideFilesSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    'publication-issues': PublicationIssuesSelect<false> | PublicationIssuesSelect<true>;
    'email-flags': EmailFlagsSelect<false> | EmailFlagsSelect<true>;
    'trademark-import-runs': TrademarkImportRunsSelect<false> | TrademarkImportRunsSelect<true>;
    'mailchimp-outbox': MailchimpOutboxSelect<false> | MailchimpOutboxSelect<true>;
    speakers: SpeakersSelect<false> | SpeakersSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    'discount-codes': DiscountCodesSelect<false> | DiscountCodesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'event-registrations': EventRegistrationsSelect<false> | EventRegistrationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'mailchimp-settings': MailchimpSetting;
  };
  globalsSelect: {
    'mailchimp-settings': MailchimpSettingsSelect<false> | MailchimpSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Staff | User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface StaffAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * The Nic360 employees who can log in to this admin panel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff".
 */
export interface Staff {
  id: number;
  name: string;
  role: 'editor' | 'gatekeeper' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'staff';
}
/**
 * Readers: members using a company subscription, or event attendees.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName: string;
  lastName: string;
  salutation?: ('Mr.' | 'Ms.' | 'Mrs.' | 'Dr.' | 'Mx.') | null;
  department?: string | null;
  phone?: string | null;
  /**
   * Sign-up profile field, separate from the Sectors taxonomy used on excerpts.
   */
  businessSector?:
    | (
        | 'manufacturer-exporter'
        | 'retail-distribution'
        | 'public-health'
        | 'academia'
        | 'government-regulatory'
        | 'law-consulting'
        | 'media'
        | 'other'
      )
    | null;
  timezone?:
    | (
        | 'Pacific/Honolulu'
        | 'America/Anchorage'
        | 'America/Los_Angeles'
        | 'America/Denver'
        | 'America/Chicago'
        | 'America/New_York'
        | 'America/Sao_Paulo'
        | 'Europe/London'
        | 'Europe/Paris'
        | 'Europe/Moscow'
        | 'Africa/Nairobi'
        | 'Asia/Dubai'
        | 'Asia/Kolkata'
        | 'Asia/Shanghai'
        | 'Asia/Tokyo'
        | 'Australia/Sydney'
      )
    | null;
  avatar?: (number | null) | Media;
  status: 'active' | 'suspended';
  /**
   * Set automatically when a verified email matches a provider's allowed domains. Empty for event-only attendees.
   */
  accessProvider?: (number | null) | AccessProvider;
  /**
   * Checkboxes on the account page. Only shown to readers with an active Base or Premium plan.
   */
  emailPublications?: (number | Publication)[] | null;
  /**
   * Event registrations where this user is the attendee. Old product orders are not migrated.
   */
  registrations?: {
    docs?: (number | EventRegistration)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * The employer organizations whose subscriptions members inherit.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "access-providers".
 */
export interface AccessProvider {
  id: number;
  name: string;
  status: 'pending' | 'trial' | 'live';
  /**
   * Premium includes everything in Base. Staff set this even for trials.
   */
  plan: 'none' | 'base' | 'premium';
  /**
   * Leave blank for no expiry. Past this date, the provider grants no access.
   */
  licenseExpiresAt?: string | null;
  /**
   * Email domains (itc.in) or exact addresses. A reader who verifies a matching email is attached to this provider automatically.
   */
  allowedDomains?:
    | {
        domain: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Reverse of each user's Access Provider field. Edit this from the user.
   */
  users?: {
    docs?: (number | User)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * The newsletter itself, e.g. "US News Clippings". An Issue is one edition of it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  thumbnail?: (number | null) | Media;
  format: 'excerpt-list' | 'pdf-report' | 'custom-html';
  frequency: 'daily' | 'weekly' | 'monthly';
  /**
   * Manual for every publication except the two automated trademark reports.
   */
  generator: 'manual' | 'weekly-trademark-report' | 'monthly-trademark-activity';
  /**
   * Defaults for building an issue; editors can still adjust each issue afterward.
   */
  selectionRules?: {
    /**
     * Defaults from frequency if left blank: 1/7/30.
     */
    window?: number | null;
    excerptTypes?: ('articles' | 'bills' | 'trademarks')[] | null;
    locations?: {
      include?: (number | Location)[] | null;
      exclude?: (number | Location)[] | null;
    };
    products?: {
      include?: (number | Product)[] | null;
      exclude?: (number | Product)[] | null;
    };
    sectors?: {
      include?: (number | Sector)[] | null;
      exclude?: (number | Sector)[] | null;
    };
    subjects?: {
      include?: (number | Subject)[] | null;
      exclude?: (number | Subject)[] | null;
    };
  };
  groupingRules?: {
    groupBy?: ('none' | 'region' | 'country' | 'primarySubject' | 'sector' | 'product' | 'excerptType') | null;
    thenGroupBy?: ('none' | 'region' | 'country' | 'primarySubject' | 'sector' | 'product' | 'excerptType') | null;
    sortBy?: ('sourceDateDesc' | 'sourceDateAsc' | 'title') | null;
  };
  mailchimp?: {
    /**
     * This publication's checkbox in the audience's Publications interest group.
     */
    interestId?: string | null;
    /**
     * The saved segment ("Publications one of …") used when sending.
     */
    segmentId?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * One record per place, reused. Hierarchy (e.g. Pennsylvania > United States > North America) lets rules and filters match a place and everything inside it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  name: string;
  level: 'region' | 'country' | 'state' | 'city';
  /**
   * E.g. Pennsylvania's parent is United States, whose parent is North America.
   */
  parent?: (number | null) | Location;
  /**
   * Fed by the address autocomplete when staff add a location.
   */
  geo?: {
    lat?: number | null;
    lng?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Flat index-term list, including a catch-all "All Products".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Flat index-term list, e.g. Manufacturers, Retail & Distribution, Social.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectors".
 */
export interface Sector {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Hierarchical index terms, e.g. RETAIL, DISTRIBUTION, & SALES > Licensing (sales).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subjects".
 */
export interface Subject {
  id: number;
  name: string;
  /**
   * Leave blank for a top-level subject.
   */
  parent?: (number | null) | Subject;
  updatedAt: string;
  createdAt: string;
}
/**
 * One ticket for one attendee.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-registrations".
 */
export interface EventRegistration {
  id: number;
  order: number | Order;
  event: number | Event;
  /**
   * Set once the attendee has an account.
   */
  attendee?: (number | null) | User;
  attendeeName: string;
  attendeeEmail: string;
  ticketType: string;
  attendance: 'in-person' | 'virtual';
  priceBasis: 'standard' | 'subscriber';
  amountPaid: number;
  discountCode?: (number | null) | DiscountCode;
  status: 'active' | 'cancelled';
  updatedAt: string;
  createdAt: string;
}
/**
 * One checkout by one buyer, which can include tickets for colleagues.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  buyer: number | User;
  event: number | Event;
  registrations?: {
    docs?: (number | EventRegistration)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  discountCode?: (number | null) | DiscountCode;
  subtotal: number;
  discount: number;
  total: number;
  status: 'pending' | 'paid' | 'cancelled' | 'refunded';
  paidAt?: string | null;
  paymentRef?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  name: string;
  channel: 'atnf' | 'gtnf' | 'infocus';
  startsAt: string;
  endDate: string;
  timezone?:
    | (
        | 'Pacific/Honolulu'
        | 'America/Anchorage'
        | 'America/Los_Angeles'
        | 'America/Denver'
        | 'America/Chicago'
        | 'America/New_York'
        | 'America/Sao_Paulo'
        | 'Europe/London'
        | 'Europe/Paris'
        | 'Africa/Nairobi'
        | 'Asia/Dubai'
        | 'Asia/Kolkata'
        | 'Asia/Shanghai'
        | 'Asia/Tokyo'
        | 'Australia/Sydney'
      )
    | null;
  hasReplay?: boolean | null;
  tagline?: string | null;
  image?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  venue?: {
    address?: string | null;
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  accommodation?: {
    phone?: string | null;
    email?: string | null;
    bookingUrl?: string | null;
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  /**
   * Regenerated from the start/end dates on save; typed names are kept.
   */
  days?:
    | {
        date: string;
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  ticketTypes?:
    | {
        name: string;
        /**
         * Buyer self-declares eligibility (Public Health, Academia); no check is made.
         */
        honorSystem?: boolean | null;
        onSale?: boolean | null;
        capacity?: number | null;
        /**
         * Leave both blank for no in-person option (e.g. InFocus).
         */
        inPerson?: {
          price?: number | null;
          /**
           * Blank = same as standard.
           */
          subscriberPrice?: number | null;
        };
        virtual?: {
          price?: number | null;
          subscriberPrice?: number | null;
        };
        id?: string | null;
      }[]
    | null;
  sponsors?: (number | Sponsor)[] | null;
  /**
   * Build the agenda from here.
   */
  sessions?: {
    docs?: (number | Session)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * One shared pool, assigned to events. No sponsor levels — all sponsors of an event display the same way.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  name: string;
  logo: number | Media;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  website?: string | null;
  /**
   * Reverse of each event's Sponsors field.
   */
  events?: {
    docs?: (number | Event)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Agenda items for all events.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: number;
  event: number | Event;
  title: string;
  description?: string | null;
  /**
   * Pick one of the event's days.
   */
  day: string;
  startTime?: string | null;
  endTime?: string | null;
  type: 'Keynote' | 'Panel' | 'Break' | 'Other';
  room?: string | null;
  moderators?: (number | Speaker)[] | null;
  speakers?: (number | Speaker)[] | null;
  speakerGroups?:
    | {
        label: string;
        speakers?: (number | Speaker)[] | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Choices should be limited to the event's own sponsors.
   */
  sponsors?: (number | Sponsor)[] | null;
  /**
   * Readable only by attendees registered for the event, once the event's Replay flag is on.
   */
  replayEmbed?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Shared across events; used for both moderators and speakers. Shows current role/company, including on past events.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers".
 */
export interface Speaker {
  id: number;
  name: string;
  role?: string | null;
  company?: string | null;
  headshot?: (number | null) | Media;
  bio?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Given to certain companies for 25-100% off a set number of tickets.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discount-codes".
 */
export interface DiscountCode {
  id: number;
  code: string;
  event: number | Event;
  /**
   * The company it was given to.
   */
  accessProvider?: (number | null) | AccessProvider;
  /**
   * 100 = comped ticket.
   */
  percentOff: number;
  /**
   * The given number of tickets; each ticket uses one.
   */
  maxUses: number;
  /**
   * Count = tickets used so far.
   */
  uses?: {
    docs?: (number | EventRegistration)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Leave empty to allow any ticket type on the event.
   */
  ticketTypes?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Article source publications, e.g. The Kenya Times (thekenyatimes.com).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources".
 */
export interface Source {
  id: number;
  name: string;
  domain?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * News found across the internet; we take the title and a preview and index it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  source?: (number | null) | Source;
  sourceDate?: string | null;
  sourceUrl?: string | null;
  excerpt: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  locations: (number | Location)[];
  sectors: (number | Sector)[];
  products: (number | Product)[];
  primarySubject: number | Subject;
  subjects: (number | Subject)[];
  ingestion?: {
    source?: ('manual' | 'statenet' | 'uspto') | null;
    externalId?: string | null;
    importedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Legislation tracked via StateNet, summarized and categorized.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bills".
 */
export interface Bill {
  id: number;
  billType: 'Bill' | 'Resolution' | 'Amendment' | 'Executive Order' | 'Regulation';
  billNumber: string;
  title: string;
  locations: (number | Location)[];
  session?: string | null;
  governmentLevel: 'Federal' | 'State/Province' | 'Local' | 'International';
  billDate: string;
  approvalDate?: string | null;
  effectiveDate?: string | null;
  lawNumber?: string | null;
  /**
   * Sponsor.
   */
  carriedBy?: string | null;
  actionUrl?: string | null;
  billUrl?: {
    title?: string | null;
    url?: string | null;
  };
  abstract: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  fullText: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  sectors: (number | Sector)[];
  products: (number | Product)[];
  primarySubject: number | Subject;
  subjects: (number | Subject)[];
  relatedArticles?: (number | Article)[] | null;
  latestActivity?: string | null;
  latestText?: string | null;
  statusText?: string | null;
  /**
   * Statute title / LexisNexis link.
   */
  statute?: {
    title?: string | null;
    url?: string | null;
  };
  committee?: string | null;
  actions?:
    | {
        date: string;
        action: string;
        actor?: string | null;
        id?: string | null;
      }[]
    | null;
  ingestion?: {
    source?: ('manual' | 'statenet' | 'uspto') | null;
    externalId?: string | null;
    importedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Scraped weekly from the USPTO XML feed: filings, renewals, cancellations.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trademarks".
 */
export interface Trademark {
  id: number;
  title: string;
  /**
   * Proposed key for USPTO upsert.
   */
  serialNumber?: string | null;
  /**
   * Nice classification.
   */
  class?: string | null;
  owner?: string | null;
  ownerAddress?: string | null;
  style?: ('yes' | 'no' | 'na') | null;
  design?: ('yes' | 'no' | 'na') | null;
  publishedDate?: string | null;
  firstUsedDate?: string | null;
  commercialUseDate?: string | null;
  filedDate?: string | null;
  registeredDate?: string | null;
  registrationNumber?: string | null;
  cancelledDate?: string | null;
  renewedDate?: string | null;
  renewal?: {
    owner?: string | null;
    address?: string | null;
  };
  image: number | Media;
  ingestion?: {
    source?: ('manual' | 'statenet' | 'uspto') | null;
    externalId?: string | null;
    importedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Reference list so dataset "country" columns show flags and names consistently.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries".
 */
export interface Country {
  id: number;
  name: string;
  iso2: string;
  iso3: string;
  /**
   * Alternate names matched against spreadsheet values on import, e.g. USA, United States of America.
   */
  aliases?:
    | {
        alias: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Staff-defined flat tables: define columns, then import a spreadsheet of rows.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datasets".
 */
export interface Dataset {
  id: number;
  title: string;
  description?: string | null;
  /**
   * An emoji or short icon name shown on the dataset card.
   */
  icon?: string | null;
  slug: string;
  /**
   * Order here is the grid column order.
   */
  columns: {
    label: string;
    /**
     * Generated from the label. Rows store values under this key.
     */
    key?: string | null;
    type: 'text' | 'number' | 'percent' | 'year' | 'date' | 'country' | 'link';
    filterable?: boolean | null;
    sortable?: boolean | null;
    defaultSort?: ('none' | 'asc' | 'desc') | null;
    id?: string | null;
  }[];
  /**
   * Set automatically by the import flow — see "Import data" on this document.
   */
  lastImport?: {
    file?: (number | null) | Media;
    /**
     * Spreadsheet header -> column key.
     */
    mapping?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    importedAt?: string | null;
    rowCount?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dataset-rows".
 */
export interface DatasetRow {
  id: number;
  dataset: number | Dataset;
  values:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides".
 */
export interface Guide {
  id: number;
  title: string;
  description?: string | null;
  thumbnail?: (number | null) | Media;
  file: number | GuideFile;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * PDFs for Guides. Served through Payload's access-checked file route, never a public URL.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guide-files".
 */
export interface GuideFile {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publication-issues".
 */
export interface PublicationIssue {
  id: number;
  publication: number | Publication;
  issueDate: string;
  title: string;
  format: 'excerpt-list' | 'pdf-report' | 'custom-html';
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * One group per section. "Build from rules" fills this in; reorder/edit freely after.
   */
  sections?:
    | {
        heading: string;
        items?:
          | (
              | {
                  relationTo: 'articles';
                  value: number | Article;
                }
              | {
                  relationTo: 'bills';
                  value: number | Bill;
                }
              | {
                  relationTo: 'trademarks';
                  value: number | Trademark;
                }
            )[]
          | null;
        id?: string | null;
      }[]
    | null;
  summary?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  file?: (number | null) | GuideFile;
  /**
   * Sanitized HTML, designed outside the CMS.
   */
  body?: string | null;
  email?: {
    /**
     * Defaults to the issue title if left blank.
     */
    subject?: string | null;
    previewText?: string | null;
    /**
     * Set when the campaign is created.
     */
    campaignId?: string | null;
    status?: ('not sent' | 'sending' | 'sent' | 'failed') | null;
    sentAt?: string | null;
    sentBy?: (number | null) | Staff;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * A queue of unsubscribes and delivery problems to follow up on.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-flags".
 */
export interface EmailFlag {
  id: number;
  user: number | User;
  reason: 'unsubscribed' | 'spam complaint' | 'cleaned';
  occurredAt: string;
  /**
   * What they were receiving, so it can be restored.
   */
  publicationsBefore?: (number | Publication)[] | null;
  status?: ('open' | 'following up' | 'resolved') | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * A log of each automated USPTO pull, so failures are visible.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trademark-import-runs".
 */
export interface TrademarkImportRun {
  id: number;
  startedAt: string;
  finishedAt?: string | null;
  status: 'running' | 'succeeded' | 'failed';
  feedSource?: string | null;
  counts?: {
    new?: number | null;
    updated?: number | null;
    renewals?: number | null;
    cancellations?: number | null;
  };
  issuesCreated?: (number | PublicationIssue)[] | null;
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Simulated Mailchimp calls. In simulated mode this is how campaigns get reviewed — the full rendered HTML and target segment are logged here instead of being sent.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mailchimp-outbox".
 */
export interface MailchimpOutbox {
  id: number;
  type: 'upsertMember' | 'createCampaign' | 'sendCampaign' | 'sendTest';
  /**
   * The target audience segment, or recipient for a test send.
   */
  segment?: string | null;
  payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * The full rendered campaign HTML, for createCampaign and sendTest entries.
   */
  html?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'staff';
        value: number | Staff;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'access-providers';
        value: number | AccessProvider;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'sectors';
        value: number | Sector;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'subjects';
        value: number | Subject;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'sources';
        value: number | Source;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'bills';
        value: number | Bill;
      } | null)
    | ({
        relationTo: 'trademarks';
        value: number | Trademark;
      } | null)
    | ({
        relationTo: 'countries';
        value: number | Country;
      } | null)
    | ({
        relationTo: 'datasets';
        value: number | Dataset;
      } | null)
    | ({
        relationTo: 'dataset-rows';
        value: number | DatasetRow;
      } | null)
    | ({
        relationTo: 'guides';
        value: number | Guide;
      } | null)
    | ({
        relationTo: 'guide-files';
        value: number | GuideFile;
      } | null)
    | ({
        relationTo: 'publications';
        value: number | Publication;
      } | null)
    | ({
        relationTo: 'publication-issues';
        value: number | PublicationIssue;
      } | null)
    | ({
        relationTo: 'email-flags';
        value: number | EmailFlag;
      } | null)
    | ({
        relationTo: 'trademark-import-runs';
        value: number | TrademarkImportRun;
      } | null)
    | ({
        relationTo: 'mailchimp-outbox';
        value: number | MailchimpOutbox;
      } | null)
    | ({
        relationTo: 'speakers';
        value: number | Speaker;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: number | Sponsor;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'sessions';
        value: number | Session;
      } | null)
    | ({
        relationTo: 'discount-codes';
        value: number | DiscountCode;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'event-registrations';
        value: number | EventRegistration;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'staff';
        value: number | Staff;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'staff';
        value: number | Staff;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff_select".
 */
export interface StaffSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  salutation?: T;
  department?: T;
  phone?: T;
  businessSector?: T;
  timezone?: T;
  avatar?: T;
  status?: T;
  accessProvider?: T;
  emailPublications?: T;
  registrations?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "access-providers_select".
 */
export interface AccessProvidersSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  plan?: T;
  licenseExpiresAt?: T;
  allowedDomains?:
    | T
    | {
        domain?: T;
        id?: T;
      };
  users?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectors_select".
 */
export interface SectorsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subjects_select".
 */
export interface SubjectsSelect<T extends boolean = true> {
  name?: T;
  parent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  level?: T;
  parent?: T;
  geo?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources_select".
 */
export interface SourcesSelect<T extends boolean = true> {
  name?: T;
  domain?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  source?: T;
  sourceDate?: T;
  sourceUrl?: T;
  excerpt?: T;
  locations?: T;
  sectors?: T;
  products?: T;
  primarySubject?: T;
  subjects?: T;
  ingestion?:
    | T
    | {
        source?: T;
        externalId?: T;
        importedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bills_select".
 */
export interface BillsSelect<T extends boolean = true> {
  billType?: T;
  billNumber?: T;
  title?: T;
  locations?: T;
  session?: T;
  governmentLevel?: T;
  billDate?: T;
  approvalDate?: T;
  effectiveDate?: T;
  lawNumber?: T;
  carriedBy?: T;
  actionUrl?: T;
  billUrl?:
    | T
    | {
        title?: T;
        url?: T;
      };
  abstract?: T;
  fullText?: T;
  sectors?: T;
  products?: T;
  primarySubject?: T;
  subjects?: T;
  relatedArticles?: T;
  latestActivity?: T;
  latestText?: T;
  statusText?: T;
  statute?:
    | T
    | {
        title?: T;
        url?: T;
      };
  committee?: T;
  actions?:
    | T
    | {
        date?: T;
        action?: T;
        actor?: T;
        id?: T;
      };
  ingestion?:
    | T
    | {
        source?: T;
        externalId?: T;
        importedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trademarks_select".
 */
export interface TrademarksSelect<T extends boolean = true> {
  title?: T;
  serialNumber?: T;
  class?: T;
  owner?: T;
  ownerAddress?: T;
  style?: T;
  design?: T;
  publishedDate?: T;
  firstUsedDate?: T;
  commercialUseDate?: T;
  filedDate?: T;
  registeredDate?: T;
  registrationNumber?: T;
  cancelledDate?: T;
  renewedDate?: T;
  renewal?:
    | T
    | {
        owner?: T;
        address?: T;
      };
  image?: T;
  ingestion?:
    | T
    | {
        source?: T;
        externalId?: T;
        importedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries_select".
 */
export interface CountriesSelect<T extends boolean = true> {
  name?: T;
  iso2?: T;
  iso3?: T;
  aliases?:
    | T
    | {
        alias?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datasets_select".
 */
export interface DatasetsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  icon?: T;
  slug?: T;
  columns?:
    | T
    | {
        label?: T;
        key?: T;
        type?: T;
        filterable?: T;
        sortable?: T;
        defaultSort?: T;
        id?: T;
      };
  lastImport?:
    | T
    | {
        file?: T;
        mapping?: T;
        importedAt?: T;
        rowCount?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dataset-rows_select".
 */
export interface DatasetRowsSelect<T extends boolean = true> {
  dataset?: T;
  values?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides_select".
 */
export interface GuidesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  thumbnail?: T;
  file?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guide-files_select".
 */
export interface GuideFilesSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  thumbnail?: T;
  format?: T;
  frequency?: T;
  generator?: T;
  selectionRules?:
    | T
    | {
        window?: T;
        excerptTypes?: T;
        locations?:
          | T
          | {
              include?: T;
              exclude?: T;
            };
        products?:
          | T
          | {
              include?: T;
              exclude?: T;
            };
        sectors?:
          | T
          | {
              include?: T;
              exclude?: T;
            };
        subjects?:
          | T
          | {
              include?: T;
              exclude?: T;
            };
      };
  groupingRules?:
    | T
    | {
        groupBy?: T;
        thenGroupBy?: T;
        sortBy?: T;
      };
  mailchimp?:
    | T
    | {
        interestId?: T;
        segmentId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publication-issues_select".
 */
export interface PublicationIssuesSelect<T extends boolean = true> {
  publication?: T;
  issueDate?: T;
  title?: T;
  format?: T;
  intro?: T;
  sections?:
    | T
    | {
        heading?: T;
        items?: T;
        id?: T;
      };
  summary?: T;
  file?: T;
  body?: T;
  email?:
    | T
    | {
        subject?: T;
        previewText?: T;
        campaignId?: T;
        status?: T;
        sentAt?: T;
        sentBy?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-flags_select".
 */
export interface EmailFlagsSelect<T extends boolean = true> {
  user?: T;
  reason?: T;
  occurredAt?: T;
  publicationsBefore?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trademark-import-runs_select".
 */
export interface TrademarkImportRunsSelect<T extends boolean = true> {
  startedAt?: T;
  finishedAt?: T;
  status?: T;
  feedSource?: T;
  counts?:
    | T
    | {
        new?: T;
        updated?: T;
        renewals?: T;
        cancellations?: T;
      };
  issuesCreated?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mailchimp-outbox_select".
 */
export interface MailchimpOutboxSelect<T extends boolean = true> {
  type?: T;
  segment?: T;
  payload?: T;
  html?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers_select".
 */
export interface SpeakersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  company?: T;
  headshot?: T;
  bio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  description?: T;
  website?: T;
  events?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  name?: T;
  channel?: T;
  startsAt?: T;
  endDate?: T;
  timezone?: T;
  hasReplay?: T;
  tagline?: T;
  image?: T;
  description?: T;
  venue?:
    | T
    | {
        address?: T;
        description?: T;
      };
  accommodation?:
    | T
    | {
        phone?: T;
        email?: T;
        bookingUrl?: T;
        description?: T;
      };
  days?:
    | T
    | {
        date?: T;
        name?: T;
        id?: T;
      };
  ticketTypes?:
    | T
    | {
        name?: T;
        honorSystem?: T;
        onSale?: T;
        capacity?: T;
        inPerson?:
          | T
          | {
              price?: T;
              subscriberPrice?: T;
            };
        virtual?:
          | T
          | {
              price?: T;
              subscriberPrice?: T;
            };
        id?: T;
      };
  sponsors?: T;
  sessions?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  event?: T;
  title?: T;
  description?: T;
  day?: T;
  startTime?: T;
  endTime?: T;
  type?: T;
  room?: T;
  moderators?: T;
  speakers?: T;
  speakerGroups?:
    | T
    | {
        label?: T;
        speakers?: T;
        id?: T;
      };
  sponsors?: T;
  replayEmbed?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discount-codes_select".
 */
export interface DiscountCodesSelect<T extends boolean = true> {
  code?: T;
  event?: T;
  accessProvider?: T;
  percentOff?: T;
  maxUses?: T;
  uses?: T;
  ticketTypes?:
    | T
    | {
        name?: T;
        id?: T;
      };
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  buyer?: T;
  event?: T;
  registrations?: T;
  discountCode?: T;
  subtotal?: T;
  discount?: T;
  total?: T;
  status?: T;
  paidAt?: T;
  paymentRef?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-registrations_select".
 */
export interface EventRegistrationsSelect<T extends boolean = true> {
  order?: T;
  event?: T;
  attendee?: T;
  attendeeName?: T;
  attendeeEmail?: T;
  ticketType?: T;
  attendance?: T;
  priceBasis?: T;
  amountPaid?: T;
  discountCode?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mailchimp-settings".
 */
export interface MailchimpSetting {
  id: number;
  /**
   * The single Mailchimp audience, e.g. "Nicotine360 Publications".
   */
  audienceId?: string | null;
  /**
   * The "Publications" interest category; one interest per Publication.
   */
  publicationsInterestCategoryId?: string | null;
  /**
   * Set via the MAILCHIMP_MODE env var, not editable here.
   */
  mode?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mailchimp-settings_select".
 */
export interface MailchimpSettingsSelect<T extends boolean = true> {
  audienceId?: T;
  publicationsInterestCategoryId?: T;
  mode?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}