/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    staff: StaffAuthOperations;
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    staff: Staff;
    users: User;
    'access-providers': AccessProvider;
    media: Media;
    sectors: Sector;
    products: Product;
    subjects: Subject;
    locations: Location;
    sources: Source;
    articles: Article;
    bills: Bill;
    trademarks: Trademark;
    countries: Country;
    datasets: Dataset;
    'dataset-rows': DatasetRow;
    guides: Guide;
    'guide-files': GuideFile;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'access-providers': {
      users: 'users';
    };
  };
  collectionsSelect: {
    staff: StaffSelect<false> | StaffSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'access-providers': AccessProvidersSelect<false> | AccessProvidersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    sectors: SectorsSelect<false> | SectorsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    subjects: SubjectsSelect<false> | SubjectsSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    sources: SourcesSelect<false> | SourcesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    bills: BillsSelect<false> | BillsSelect<true>;
    trademarks: TrademarksSelect<false> | TrademarksSelect<true>;
    countries: CountriesSelect<false> | CountriesSelect<true>;
    datasets: DatasetsSelect<false> | DatasetsSelect<true>;
    'dataset-rows': DatasetRowsSelect<false> | DatasetRowsSelect<true>;
    guides: GuidesSelect<false> | GuidesSelect<true>;
    'guide-files': GuideFilesSelect<false> | GuideFilesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Staff | User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface StaffAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * The Nic360 employees who can log in to this admin panel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff".
 */
export interface Staff {
  id: number;
  name: string;
  role: 'editor' | 'gatekeeper' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'staff';
}
/**
 * Readers: members using a company subscription, or event attendees.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName: string;
  lastName: string;
  salutation?: ('Mr.' | 'Ms.' | 'Mrs.' | 'Dr.' | 'Mx.') | null;
  department?: string | null;
  phone?: string | null;
  /**
   * Sign-up profile field, separate from the Sectors taxonomy used on excerpts.
   */
  businessSector?:
    | (
        | 'manufacturer-exporter'
        | 'retail-distribution'
        | 'public-health'
        | 'academia'
        | 'government-regulatory'
        | 'law-consulting'
        | 'media'
        | 'other'
      )
    | null;
  timezone?:
    | (
        | 'Pacific/Honolulu'
        | 'America/Anchorage'
        | 'America/Los_Angeles'
        | 'America/Denver'
        | 'America/Chicago'
        | 'America/New_York'
        | 'America/Sao_Paulo'
        | 'Europe/London'
        | 'Europe/Paris'
        | 'Europe/Moscow'
        | 'Africa/Nairobi'
        | 'Asia/Dubai'
        | 'Asia/Kolkata'
        | 'Asia/Shanghai'
        | 'Asia/Tokyo'
        | 'Australia/Sydney'
      )
    | null;
  avatar?: (number | null) | Media;
  status: 'active' | 'suspended';
  /**
   * Set automatically when a verified email matches a provider's allowed domains. Empty for event-only attendees.
   */
  accessProvider?: (number | null) | AccessProvider;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * The employer organizations whose subscriptions members inherit.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "access-providers".
 */
export interface AccessProvider {
  id: number;
  name: string;
  status: 'pending' | 'trial' | 'live';
  /**
   * Premium includes everything in Base. Staff set this even for trials.
   */
  plan: 'none' | 'base' | 'premium';
  /**
   * Leave blank for no expiry. Past this date, the provider grants no access.
   */
  licenseExpiresAt?: string | null;
  /**
   * Email domains (itc.in) or exact addresses. A reader who verifies a matching email is attached to this provider automatically.
   */
  allowedDomains?:
    | {
        domain: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Reverse of each user's Access Provider field. Edit this from the user.
   */
  users?: {
    docs?: (number | User)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Flat index-term list, e.g. Manufacturers, Retail & Distribution, Social.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectors".
 */
export interface Sector {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Flat index-term list, including a catch-all "All Products".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Hierarchical index terms, e.g. RETAIL, DISTRIBUTION, & SALES > Licensing (sales).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subjects".
 */
export interface Subject {
  id: number;
  name: string;
  /**
   * Leave blank for a top-level subject.
   */
  parent?: (number | null) | Subject;
  updatedAt: string;
  createdAt: string;
}
/**
 * One record per place, reused. Hierarchy (e.g. Pennsylvania > United States > North America) lets rules and filters match a place and everything inside it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  name: string;
  level: 'region' | 'country' | 'state' | 'city';
  /**
   * E.g. Pennsylvania's parent is United States, whose parent is North America.
   */
  parent?: (number | null) | Location;
  /**
   * Fed by the address autocomplete when staff add a location.
   */
  geo?: {
    lat?: number | null;
    lng?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Article source publications, e.g. The Kenya Times (thekenyatimes.com).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources".
 */
export interface Source {
  id: number;
  name: string;
  domain?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * News found across the internet; we take the title and a preview and index it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  source?: (number | null) | Source;
  sourceDate?: string | null;
  sourceUrl?: string | null;
  excerpt: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  locations: (number | Location)[];
  sectors: (number | Sector)[];
  products: (number | Product)[];
  primarySubject: number | Subject;
  subjects: (number | Subject)[];
  ingestion?: {
    source?: ('manual' | 'statenet' | 'uspto') | null;
    externalId?: string | null;
    importedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Legislation tracked via StateNet, summarized and categorized.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bills".
 */
export interface Bill {
  id: number;
  billType: 'Bill' | 'Resolution' | 'Amendment' | 'Executive Order' | 'Regulation';
  billNumber: string;
  title: string;
  locations: (number | Location)[];
  session?: string | null;
  governmentLevel: 'Federal' | 'State/Province' | 'Local' | 'International';
  billDate: string;
  approvalDate?: string | null;
  effectiveDate?: string | null;
  lawNumber?: string | null;
  /**
   * Sponsor.
   */
  carriedBy?: string | null;
  actionUrl?: string | null;
  billUrl?: {
    title?: string | null;
    url?: string | null;
  };
  abstract: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  fullText: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  sectors: (number | Sector)[];
  products: (number | Product)[];
  primarySubject: number | Subject;
  subjects: (number | Subject)[];
  relatedArticles?: (number | Article)[] | null;
  latestActivity?: string | null;
  latestText?: string | null;
  statusText?: string | null;
  /**
   * Statute title / LexisNexis link.
   */
  statute?: {
    title?: string | null;
    url?: string | null;
  };
  committee?: string | null;
  actions?:
    | {
        date: string;
        action: string;
        actor?: string | null;
        id?: string | null;
      }[]
    | null;
  ingestion?: {
    source?: ('manual' | 'statenet' | 'uspto') | null;
    externalId?: string | null;
    importedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Scraped weekly from the USPTO XML feed: filings, renewals, cancellations.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trademarks".
 */
export interface Trademark {
  id: number;
  title: string;
  /**
   * Proposed key for USPTO upsert.
   */
  serialNumber?: string | null;
  /**
   * Nice classification.
   */
  class?: string | null;
  owner?: string | null;
  ownerAddress?: string | null;
  style?: ('yes' | 'no' | 'na') | null;
  design?: ('yes' | 'no' | 'na') | null;
  publishedDate?: string | null;
  firstUsedDate?: string | null;
  commercialUseDate?: string | null;
  filedDate?: string | null;
  registeredDate?: string | null;
  registrationNumber?: string | null;
  cancelledDate?: string | null;
  renewedDate?: string | null;
  renewal?: {
    owner?: string | null;
    address?: string | null;
  };
  image: number | Media;
  ingestion?: {
    source?: ('manual' | 'statenet' | 'uspto') | null;
    externalId?: string | null;
    importedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Reference list so dataset "country" columns show flags and names consistently.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries".
 */
export interface Country {
  id: number;
  name: string;
  iso2: string;
  iso3: string;
  /**
   * Alternate names matched against spreadsheet values on import, e.g. USA, United States of America.
   */
  aliases?:
    | {
        alias: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Staff-defined flat tables: define columns, then import a spreadsheet of rows.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datasets".
 */
export interface Dataset {
  id: number;
  title: string;
  description?: string | null;
  /**
   * An emoji or short icon name shown on the dataset card.
   */
  icon?: string | null;
  slug: string;
  /**
   * Order here is the grid column order.
   */
  columns: {
    label: string;
    /**
     * Generated from the label. Rows store values under this key.
     */
    key?: string | null;
    type: 'text' | 'number' | 'percent' | 'year' | 'date' | 'country' | 'link';
    filterable?: boolean | null;
    sortable?: boolean | null;
    defaultSort?: ('none' | 'asc' | 'desc') | null;
    id?: string | null;
  }[];
  /**
   * Set automatically by the import flow — see "Import data" on this document.
   */
  lastImport?: {
    file?: (number | null) | Media;
    /**
     * Spreadsheet header -> column key.
     */
    mapping?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    importedAt?: string | null;
    rowCount?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dataset-rows".
 */
export interface DatasetRow {
  id: number;
  dataset: number | Dataset;
  values:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides".
 */
export interface Guide {
  id: number;
  title: string;
  description?: string | null;
  thumbnail?: (number | null) | Media;
  file: number | GuideFile;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * PDFs for Guides. Served through Payload's access-checked file route, never a public URL.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guide-files".
 */
export interface GuideFile {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'staff';
        value: number | Staff;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'access-providers';
        value: number | AccessProvider;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'sectors';
        value: number | Sector;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'subjects';
        value: number | Subject;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'sources';
        value: number | Source;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'bills';
        value: number | Bill;
      } | null)
    | ({
        relationTo: 'trademarks';
        value: number | Trademark;
      } | null)
    | ({
        relationTo: 'countries';
        value: number | Country;
      } | null)
    | ({
        relationTo: 'datasets';
        value: number | Dataset;
      } | null)
    | ({
        relationTo: 'dataset-rows';
        value: number | DatasetRow;
      } | null)
    | ({
        relationTo: 'guides';
        value: number | Guide;
      } | null)
    | ({
        relationTo: 'guide-files';
        value: number | GuideFile;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'staff';
        value: number | Staff;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'staff';
        value: number | Staff;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff_select".
 */
export interface StaffSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  salutation?: T;
  department?: T;
  phone?: T;
  businessSector?: T;
  timezone?: T;
  avatar?: T;
  status?: T;
  accessProvider?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "access-providers_select".
 */
export interface AccessProvidersSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  plan?: T;
  licenseExpiresAt?: T;
  allowedDomains?:
    | T
    | {
        domain?: T;
        id?: T;
      };
  users?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectors_select".
 */
export interface SectorsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subjects_select".
 */
export interface SubjectsSelect<T extends boolean = true> {
  name?: T;
  parent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  level?: T;
  parent?: T;
  geo?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources_select".
 */
export interface SourcesSelect<T extends boolean = true> {
  name?: T;
  domain?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  source?: T;
  sourceDate?: T;
  sourceUrl?: T;
  excerpt?: T;
  locations?: T;
  sectors?: T;
  products?: T;
  primarySubject?: T;
  subjects?: T;
  ingestion?:
    | T
    | {
        source?: T;
        externalId?: T;
        importedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bills_select".
 */
export interface BillsSelect<T extends boolean = true> {
  billType?: T;
  billNumber?: T;
  title?: T;
  locations?: T;
  session?: T;
  governmentLevel?: T;
  billDate?: T;
  approvalDate?: T;
  effectiveDate?: T;
  lawNumber?: T;
  carriedBy?: T;
  actionUrl?: T;
  billUrl?:
    | T
    | {
        title?: T;
        url?: T;
      };
  abstract?: T;
  fullText?: T;
  sectors?: T;
  products?: T;
  primarySubject?: T;
  subjects?: T;
  relatedArticles?: T;
  latestActivity?: T;
  latestText?: T;
  statusText?: T;
  statute?:
    | T
    | {
        title?: T;
        url?: T;
      };
  committee?: T;
  actions?:
    | T
    | {
        date?: T;
        action?: T;
        actor?: T;
        id?: T;
      };
  ingestion?:
    | T
    | {
        source?: T;
        externalId?: T;
        importedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trademarks_select".
 */
export interface TrademarksSelect<T extends boolean = true> {
  title?: T;
  serialNumber?: T;
  class?: T;
  owner?: T;
  ownerAddress?: T;
  style?: T;
  design?: T;
  publishedDate?: T;
  firstUsedDate?: T;
  commercialUseDate?: T;
  filedDate?: T;
  registeredDate?: T;
  registrationNumber?: T;
  cancelledDate?: T;
  renewedDate?: T;
  renewal?:
    | T
    | {
        owner?: T;
        address?: T;
      };
  image?: T;
  ingestion?:
    | T
    | {
        source?: T;
        externalId?: T;
        importedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries_select".
 */
export interface CountriesSelect<T extends boolean = true> {
  name?: T;
  iso2?: T;
  iso3?: T;
  aliases?:
    | T
    | {
        alias?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datasets_select".
 */
export interface DatasetsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  icon?: T;
  slug?: T;
  columns?:
    | T
    | {
        label?: T;
        key?: T;
        type?: T;
        filterable?: T;
        sortable?: T;
        defaultSort?: T;
        id?: T;
      };
  lastImport?:
    | T
    | {
        file?: T;
        mapping?: T;
        importedAt?: T;
        rowCount?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dataset-rows_select".
 */
export interface DatasetRowsSelect<T extends boolean = true> {
  dataset?: T;
  values?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides_select".
 */
export interface GuidesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  thumbnail?: T;
  file?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guide-files_select".
 */
export interface GuideFilesSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}